### ISSUE TITLE
left, right: 0

### ISSUE THREAD

**Issue by Grawl** [postcss/postcss-plugin-suggestion-box#1]
Input:

``` css
.foo {
  position: absolute;
  top, left: 0;
  margin-x, padding-x: 1em;
}
```

Output:

``` css
.foo {
  position: absolute;
  top: 0;
  left: 0;
  margin-left: 1em;
  margin-right: 1em;
  padding-left: 1em;
  padding-right: 1em;
}
```

`margin-x` and `padding-x` coming from [`postcss-axis`](https://www.npmjs.com/package/postcss-axis)
