### ISSUE TITLE
image(<color>) polyfill

### ISSUE THREAD

**Issue by valtlai** [postcss/postcss-plugin-suggestion-box#11]
Spec: https://drafts.csswg.org/css-images-4/#image-notation

You could create a solid-color image, for example:

```css
.foo {
   background: image(red);
}
```

And it’s converted to the following which is supported by the modern browsers:

```css
.foo {
   background: linear-gradient(red, red);
}
```

**Comment by ai** [comment]
What is a reason for it? Why not `background: red`?

**Comment by valtlai** [comment]
@ai Maybe you want to cover only a part of the background or stack a solid color top of another background.

Demos from the *CSS Secrets* book:
* [Vintage envelope themed border](http://dabblet.com/gist/e3cfcb094e65d85df847)
* [Marching ants border](http://dabblet.com/gist/f26dddc71730c3847153)
* [Custom underlines](http://dabblet.com/gist/58f3d67d5bb0f8338776)

Or something like this:

```css
select {
  /* ... */
  background: linear-gradient(currentcolor, currentcolor) right 1.4em center / 1px calc(100% - 6px) no-repeat;
  background: image(currentcolor) right 1.4em center / 1px calc(100% - 6px) no-repeat; /* Future syntax! */
  /* ... */
}
```

[Full demo](https://codepen.io/valtlai/pen/rgrXwG?editors=1100)
