### ISSUE TITLE
@font-face format() keywords

### ISSUE THREAD

**Issue by valtlai** [postcss/postcss-plugin-suggestion-box#12]
Spec: https://www.w3.org/TR/css-fonts-4/#font-format-values

Supporting keywords inside `@font-face`’s `format()` function by transforming them into string.

Example input:
```css
@font-face {
   src: url(foo.woff2) format(woff2);
}
```

Output:
```css
@font-face {
   src: url(foo.woff2) format("woff2");
}
```
