### ISSUE TITLE
Dynamic custom properties polyfill

### ISSUE THREAD

**Issue by ai** [postcss/postcss-plugin-suggestion-box#6]
We could not polyfill full power of Custom Properties, but we could solve case, when we put some class to `body` and override variables inside (global theming) like `boby.themeA`.

You pass this `<body>` switching classes to plugin:

``` js
require('postcss-dynamic-custom-props')({ rootClasses: ['theme-A', 'theme-B'] })
```

Then plugin will find all overrides definitions like and remember a variable names:

``` css
.theme-A {
   --bg-color: red;
   --text-color: blue;
}
```

Then it will find all rules, where this variables used, like:

``` css
p {
   color: var(--text-color);
}
```

On final step it merge themes classes and overrides and generate this:

``` css
.themeA p {
   color: blue;
}
```

Idea came from this question: https://github.com/postcss/postcss-simple-vars/issues/54#issuecomment-231583606

/cc @RyoIkarashi
