### ISSUE TITLE
Sass color functions sugar

### ISSUE THREAD

**Issue by ai** [postcss/postcss-plugin-suggestion-box#8]
In PostCSS we use W3C `color()` funciton. But many developers love Sass function and hate new official syntax. Let’s write a converter:

Input:

``` css
.foo {
  background: darken($color, 10%);
}
```

Output:

``` css
.foo {
  background: color($color l(-10%));
}
```
